name: Build App

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write

    strategy:
      matrix:
        os:
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install PyInstaller
        run: python -m pip install --upgrade pip pyinstaller

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src-python/requirements.txt

      - name: Build Python executable
        shell: bash
        run: |
          pyinstaller \
            --onefile \
            --distpath dist/python \
            --workpath dist/python/pyinstaller \
            --specpath dist/python/pyinstaller \
            --paths src-python \
            src-python/run_balloon_solver.py

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node dependencies
        run: npm ci

      - name: Build App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
